# Cleanup Obsolete DynamoDB Tables
# These tables were auto-generated by Amplify but are not being used
# The active tables are: base-wecare-digital-*

Write-Host "=== OBSOLETE DYNAMODB TABLES ===" -ForegroundColor Yellow
Write-Host "The following tables are NOT being used and can be deleted:" -ForegroundColor Cyan

$obsoleteTables = @(
    "AIInteraction-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE",
    "AIInteractions",
    "AuditLog-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE",
    "BulkJob-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE",
    "BulkRecipient-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE",
    "Contact-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE",
    "DLQMessage-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE",
    "MediaFile-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE",
    "MediaFiles",
    "Message-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE",
    "RateLimitTracker-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE",
    "RateLimitTrackers",
    "SystemConfig",
    "SystemConfig-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE",
    "User-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE",
    "VoiceCall-cpjtzc5lsnaxppkfwsz2sdqx7q-NONE"
)

foreach ($table in $obsoleteTables) {
    Write-Host "  - $table" -ForegroundColor Gray
}

Write-Host ""
Write-Host "=== ACTIVE TABLES (DO NOT DELETE) ===" -ForegroundColor Green
$activeTables = @(
    "base-wecare-digital-ContactsTable",
    "base-wecare-digital-WhatsAppInboundTable",
    "base-wecare-digital-WhatsAppOutboundTable",
    "base-wecare-digital-AuditTable",
    "base-wecare-digital-BulkJobsTable",
    "base-wecare-digital-BulkJobChunksTable",
    "base-wecare-digital-VoiceCalls",
    "base-wecare-digital-DocsTable",
    "base-wecare-digital-FormsTable",
    "base-wecare-digital-InvoiceTable",
    "base-wecare-digital-LinkTable",
    "base-wecare-digital-PayTable"
)

foreach ($table in $activeTables) {
    Write-Host "  - $table" -ForegroundColor Green
}

Write-Host ""
$confirm = Read-Host "Do you want to DELETE the obsolete tables? (yes/no)"

if ($confirm -eq "yes") {
    foreach ($table in $obsoleteTables) {
        Write-Host "Deleting $table..." -ForegroundColor Yellow
        aws dynamodb delete-table --table-name $table --region us-east-1 2>$null
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  Deleted!" -ForegroundColor Green
        } else {
            Write-Host "  Failed or already deleted" -ForegroundColor Red
        }
    }
    Write-Host ""
    Write-Host "Cleanup complete!" -ForegroundColor Green
} else {
    Write-Host "Cleanup cancelled." -ForegroundColor Yellow
}
